chore: v0.6.2 (#156)
* Bump v0.6.2
* Update expectations
* Created initial READMEs for all public NPM modules.
* Separated contribution and dev env info into CONTRIBUTING.md
* `bump.sh`: A script to bump the repo version and update all test expectations based on the new version. It sets `UPDATE_DIFF=1` to run tests in "update" mode

diff --git a/packages/jsii-build-tools/bin/diff-test b/packages/jsii-build-tools/bin/diff-test
--- a/packages/jsii-build-tools/bin/diff-test
+++ b/packages/jsii-build-tools/bin/diff-test
@@ -14,7 +14,18 @@ actual="$(resolve-path $2)"
 diff ${actual} ${expected} || {
   echo
   echo "========================================================================="
-  echo "test failed. to update:"
-  echo "    cp ${actual} ${expected}"
-  exit 1
+
+  if [ -n "${UPDATE_DIFF:-}" ]; then
+    echo "⚡️ UPDATE_DIFF is set, overwriting ${expected}"
+    cp ${actual} ${expected}
+    exit 0
+  else
+    echo "test failed. to update:"
+    echo "    cp ${actual} ${expected}"
+    echo
+    echo "or, execute again with:"
+    echo "   UPDATE_DIFF=1"
+    echo
+    exit 1
+  fi
 }
